services:
  backend_stage:
    image: ghcr.io/othavio-oth/strategy:stage
    container_name: strategy_backend_stage
    restart: always
    env_file:
      - .env.stage
    ports:
      - "8001:8000"
    depends_on:
      - db_stage
    networks:
      - strategy_stage_net

  db_stage:
    image: postgres:15
    container_name: strategy_db_stage
    restart: always
    environment:
      POSTGRES_DB: strategy_stage
      POSTGRES_USER: strategy
      POSTGRES_PASSWORD: strategy
    volumes:
      - postgres_stage_data:/var/lib/postgresql/data
    networks:
      - strategy_stage_net

volumes:
  postgres_stage_data:

networks:
  strategy_stage_net:
    driver: bridge
