name: Deploy PROD

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/othavio-oth/strategy
          docker build -t $IMAGE:latest .
          docker push $IMAGE:latest

      - name: Deploy PROD
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/strategy/strategy_backend_inventory
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            sudo fuser -k 8000/tcp || true
            docker compose -p strategy-prod down || true
            docker compose -p strategy-prod pull
            docker compose -p strategy-prod up -d
