"""add name to ticket

Revision ID: 073f1a91e557
Revises: 701e7f2089b0
Create Date: 2025-07-07 15:19:04.975972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073f1a91e557'
down_revision: Union[str, None] = '701e7f2089b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('name', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'tickets', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'name')
    # ### end Alembic commands ###
