"""logic delete in products

Revision ID: 0b5c33da1d2c
Revises: d9ab393e8ab9
Create Date: 2025-08-01 17:55:49.480480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5c33da1d2c'
down_revision: Union[str, None] = 'd9ab393e8ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_centers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cost_centers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_active')
    op.drop_column('cost_centers', 'deleted_at')
    op.drop_column('cost_centers', 'is_active')
    # ### end Alembic commands ###
