"""create table stock products

Revision ID: 20729171c82e
Revises: 744aa6fcab0e
Create Date: 2025-04-28 16:49:47.234609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20729171c82e'
down_revision: Union[str, None] = '744aa6fcab0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_products_id'), 'stock_products', ['id'], unique=False)
    op.create_table('stock_products_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_product_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['stock_product_id'], ['stock_products.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_products_history_id'), 'stock_products_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_products_history_id'), table_name='stock_products_history')
    op.drop_table('stock_products_history')
    op.drop_index(op.f('ix_stock_products_id'), table_name='stock_products')
    op.drop_table('stock_products')
    # ### end Alembic commands ###
