"""add unit and total price

Revision ID: 3d4b4154e681
Revises: 41deab614fc8
Create Date: 2025-07-14 16:57:28.669650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4b4154e681'
down_revision: Union[str, None] = '41deab614fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_products', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ticket_products', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_products', 'total_price')
    op.drop_column('ticket_products', 'unit_price')
    # ### end Alembic commands ###
