"""changes on Stock

Revision ID: 507a55d74d14
Revises: 95c4512412ca
Create Date: 2025-07-21 12:33:40.589433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507a55d74d14'
down_revision: Union[str, None] = '95c4512412ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_products_history_id', table_name='stock_products_history')
    op.drop_table('stock_products_history')
    op.drop_column('products', 'date_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date_cost', sa.DATE(), autoincrement=False, nullable=False))
    op.create_table('stock_products_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cost_center_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name='stock_products_history_cost_center_id_fkey'),
    sa.ForeignKeyConstraint(['stock_product_id'], ['stock_products.id'], name='stock_products_history_stock_product_id_fkey'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='stock_products_history_ticket_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_products_history_pkey')
    )
    op.create_index('ix_stock_products_history_id', 'stock_products_history', ['id'], unique=False)
    # ### end Alembic commands ###
