"""add approved_at

Revision ID: 72e30d24083f
Revises: d9ab9eeb46d9
Create Date: 2025-08-14 19:41:08.018228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e30d24083f'
down_revision: Union[str, None] = 'd9ab9eeb46d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sales_day', 'client_sales_history', ['cost_center_id', 'product_id', 'date'])
    op.add_column('tickets', sa.Column('aproved_at', sa.DateTime(), nullable=True))
    op.drop_column('tickets', 'aprovedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('aprovedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'aproved_at')
    op.drop_constraint('uq_sales_day', 'client_sales_history', type_='unique')
    # ### end Alembic commands ###
