"""alter table tickets add column userid

Revision ID: 744aa6fcab0e
Revises: 929f2df92e0d
Create Date: 2025-04-21 09:41:03.219292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744aa6fcab0e'
down_revision: Union[str, None] = '929f2df92e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'created_by')
    # ### end Alembic commands ###
