"""group and registration are optional

Revision ID: 9b6d251d9ec5
Revises: 057418461b1c
Create Date: 2025-07-21 14:17:38.705605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6d251d9ec5'
down_revision: Union[str, None] = '057418461b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'type_registration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'type_registration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
