"""add approved_at

Revision ID: c3b640c7060c
Revises: 72e30d24083f
Create Date: 2025-08-14 19:41:44.925263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3b640c7060c'
down_revision: Union[str, None] = '72e30d24083f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.drop_column('tickets', 'aproved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('aproved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'approved_at')
    # ### end Alembic commands ###
