"""entry cost in ticket-products

Revision ID: c6f2d1f5b907
Revises: 6dd7b98fe4c8
Create Date: 2025-08-04 17:23:42.373036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f2d1f5b907'
down_revision: Union[str, None] = '6dd7b98fe4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_products', sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_products', 'entry_price')
    # ### end Alembic commands ###
