"""Initial migration

Revision ID: d30f59bb48bb
Revises: 
Create Date: 2025-08-05 23:54:36.183700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30f59bb48bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_retail_chain_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_category_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'category')
    op.drop_column('products', 'retail_chain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('retail_chain_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_fkey', 'products', 'categories', ['category'], ['id'])
    op.create_foreign_key('products_retail_chain_id_fkey', 'products', 'retail_chains', ['retail_chain_id'], ['id'])
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
