"""changes on ProductPriceHistory

Revision ID: d82757aae9cd
Revises: 3d414a4daa98
Create Date: 2025-08-06 16:52:39.721718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd82757aae9cd'
down_revision: Union[str, None] = '3d414a4daa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_cost_history_cost_center_id_fkey', 'product_cost_history', type_='foreignkey')
    op.drop_column('product_cost_history', 'cost_center_id')
    op.add_column('product_price_history', sa.Column('retail_chain_id', sa.Integer(), nullable=True))
    op.add_column('product_price_history', sa.Column('cost_center_id', sa.Integer(), nullable=True))
    op.alter_column('product_price_history', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_product_chain_active', table_name='product_price_history')
    op.drop_index('ix_product_price_history_chain_id', table_name='product_price_history')
    op.drop_index('ix_product_price_history_end_date', table_name='product_price_history')
    op.drop_index('ix_product_price_history_product_id', table_name='product_price_history')
    op.drop_constraint('uix_product_chain_start', 'product_price_history', type_='unique')
    op.create_unique_constraint('uix_product_chain_start', 'product_price_history', ['product_id', 'retail_chain_id', 'start_date'])
    op.create_unique_constraint('uix_product_cost_center_start', 'product_price_history', ['product_id', 'cost_center_id', 'start_date'])
    op.drop_constraint('product_price_history_chain_id_fkey', 'product_price_history', type_='foreignkey')
    op.create_foreign_key(None, 'product_price_history', 'retail_chains', ['retail_chain_id'], ['id'])
    op.create_foreign_key(None, 'product_price_history', 'cost_centers', ['cost_center_id'], ['id'])
    op.drop_column('product_price_history', 'chain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_history', sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_price_history', type_='foreignkey')
    op.drop_constraint(None, 'product_price_history', type_='foreignkey')
    op.create_foreign_key('product_price_history_chain_id_fkey', 'product_price_history', 'retail_chains', ['chain_id'], ['id'])
    op.drop_constraint('uix_product_cost_center_start', 'product_price_history', type_='unique')
    op.drop_constraint('uix_product_chain_start', 'product_price_history', type_='unique')
    op.create_unique_constraint('uix_product_chain_start', 'product_price_history', ['product_id', 'chain_id', 'start_date'])
    op.create_index('ix_product_price_history_product_id', 'product_price_history', ['product_id'], unique=False)
    op.create_index('ix_product_price_history_end_date', 'product_price_history', ['end_date'], unique=False)
    op.create_index('ix_product_price_history_chain_id', 'product_price_history', ['chain_id'], unique=False)
    op.create_index('ix_product_chain_active', 'product_price_history', ['product_id', 'chain_id', 'end_date'], unique=False)
    op.alter_column('product_price_history', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('product_price_history', 'cost_center_id')
    op.drop_column('product_price_history', 'retail_chain_id')
    op.add_column('product_cost_history', sa.Column('cost_center_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_cost_history_cost_center_id_fkey', 'product_cost_history', 'cost_centers', ['cost_center_id'], ['id'])
    # ### end Alembic commands ###
