"""add sales start date

Revision ID: d9ab9eeb46d9
Revises: 1f92296c0184
Create Date: 2025-08-14 18:14:02.106298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ab9eeb46d9'
down_revision: Union[str, None] = '1f92296c0184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('aprovedAt', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('sales_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sales_start_date')
    op.drop_column('tickets', 'aprovedAt')
    # ### end Alembic commands ###
