"""add product_unit_cost em stock_movement

Revision ID: f04254c4be65
Revises: d3d44b8b1458
Create Date: 2025-08-11 19:24:20.299763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04254c4be65'
down_revision: Union[str, None] = 'd3d44b8b1458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('product_unit_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'product_unit_cost')
    # ### end Alembic commands ###
